// The single keys: slash to search, Escape backs out, x selects, r reaches the reply box, f opens
// Forward, and the palette says what to do when nothing is selected.
const row = (n) => `[data-slot="notes-row"]:nth-of-type(${n}) button[aria-pressed]`;
const active = () => document.activeElement?.getAttribute('data-slot') || document.activeElement?.tagName;
await pw.press('body', 'Meta+k');
await wait(400);
const emptyPalette = text($('[data-slot="command-group"]') || $('[cmdk-group]') || $('[role="listbox"]'));
await pw.press('body', 'Escape');
await wait(300);
await pw.press('body', '/');
await wait(200);
const slash = active();
await pw.press('[data-slot="search"]', 'Escape');
await wait(200);
const afterEsc = active();
await pw.click(row(1));
await wait(300);
await pw.press(row(1), 'x');
await wait(200);
const afterX = $$('[data-slot="notes-row"][data-state="selected"]').length;
await pw.press('body', 'x');
await wait(200);
const afterX2 = $$('[data-slot="notes-row"][data-state="selected"]').length;
await pw.press('body', 'r');
await wait(300);
const afterR = active();
await pw.press('[data-slot="reply-box"]', 'Escape');
await pw.click(row(2));
await wait(200);
await pw.press(row(2), 'f');
await wait(400);
const forward = Boolean($('[data-slot="address-dialog"]'));
await pw.press('body', 'Escape');
await wait(300);
await pw.press('body', 'Meta+k');
await wait(400);
const items = $$('[data-slot="command-item"]').map(text);
const ok = /Select a note/.test(emptyPalette) && slash === 'search' && afterEsc !== 'search' && afterX === 0 && afterX2 === 1 && afterR === 'reply-box' && forward && items.some((t) => /Reply to 1 note and close/.test(t)) && items.some((t) => /Forward a copy of 1 note/.test(t)) && items.some((t) => /Change recipients/.test(t));
return { verdict: ok ? 'PASS' : 'FAIL see fields', emptyPalette: emptyPalette.slice(0, 80), slash, afterEsc, afterX, afterX2, afterR, forward, items: items.slice(0, 9) };
